platform:
  gazebo_ros_control:
    pid_gains:
      front_left_wheel: {p: 0.5, i: 0.01, d: 0}
      front_right_wheel: {p: 0.5, i: 0.01, d: 0}
      rear_left_wheel: {p: 0.5, i: 0.01, d: 0}
      rear_right_wheel: {p: 0.5, i: 0.01, d: 0}

panda:  
  position:
    gains:
      panda_joint1: { p: 600, d: 30, i: 0 }
      panda_joint2: { p: 600, d: 30, i: 0 }
      panda_joint3: { p: 600, d: 30, i: 0 }
      panda_joint4: { p: 600, d: 30, i: 0 }
      panda_joint5: { p: 250, d: 10, i: 0 }
      panda_joint6: { p: 150, d: 10, i: 0 }
      panda_joint7: { p:  50, d:  5, i: 0 }
  velocity:
    gains:
      panda_joint1: { p: 30, d: 0, i: 0 }
      panda_joint2: { p: 30, d: 0, i: 0 }
      panda_joint3: { p: 30, d: 0, i: 0 }
      panda_joint4: { p: 30, d: 0, i: 0 }
      panda_joint5: { p: 10, d: 0, i: 0 }
      panda_joint6: { p: 10, d: 0, i: 0 }
      panda_joint7: { p:  5, d:  0, i: 0 }